apiVersion: v1
kind: Pod
metadata:
  name: volumepod
spec:
  containers:
    - name: mypod
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: myclaim