apiVersion: v1
kind: Pod
metadata:
 name: multi-cont-pod
 labels:
  app: multi-cont-pod
  type: service
spec:
 containers:
  - name: service-pod
    image: nginx
  - name: utility-pod
    image: nginx
   