--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: weblearner
    type: rest_service
  name: weblearner
spec: 
  containers: 
    - 
      image: raghuram04/myweblearner
      livenessProbe: 
        failureThreshold: 1
        httpGet: 
          path: /weblearner/health
          port: 8085
        initialDelaySeconds: 10
        periodSeconds: 10
      name: weblearner
      readinessProbe: 
        initialDelaySeconds: 5
        periodSeconds: 10
        tcpSocket: 
          port: 8085
